# Generated by Django 5.2.1 on 2025-05-12 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(choices=[('dvor', 'Дворцовая 4А'), ('repina', 'ул. Репина 4'), ('lenina', 'пр. Ленинского Комсомола 34')], max_length=100, verbose_name='Филиал')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('duration', models.CharField(max_length=50, verbose_name='Срок действия')),
                ('features', models.TextField(verbose_name='Особенности')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
            ],
        ),
    ]
