# Generated by Django 5.2.1 on 2025-05-12 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainfitnes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': 'Абонемент', 'verbose_name_plural': 'Абонементы'},
        ),
        migrations.AddField(
            model_name='subscription',
            name='freeze_available',
            field=models.BooleanField(default=False, verbose_name='Заморозка карты'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='freeze_details',
            field=models.CharField(blank=True, max_length=200, verbose_name='Условия заморозки'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='working_hours',
            field=models.CharField(default='08:00-22:00', max_length=100, verbose_name='Режим работы'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='price',
            field=models.IntegerField(verbose_name='Цена, руб.'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название абонемента'),
        ),
    ]
