# Generated by Django 5.2.1 on 2025-05-12 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainfitnes', '0002_alter_subscription_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={},
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='freeze_available',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='freeze_details',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='working_hours',
        ),
        migrations.AlterField(
            model_name='subscription',
            name='price',
            field=models.IntegerField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
    ]
