# Generated by Django 5.2.1 on 2025-05-12 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainfitnes', '0003_alter_subscription_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessions_count', models.PositiveIntegerField(verbose_name='Количество тренировок')),
                ('trainer_type', models.CharField(choices=[('regular', 'Персональный тренер'), ('master', 'Мастер-тренер')], max_length=20, verbose_name='Тип тренера')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
            ],
        ),
    ]
