# Generated by Django 5.2.1 on 2025-05-12 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainfitnes', '0004_personaltraining'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personaltraining',
            old_name='sessions_count',
            new_name='sessions',
        ),
        migrations.AlterField(
            model_name='personaltraining',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
    ]
