# Generated by Django 5.2.1 on 2025-05-13 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainfitnes', '0005_rename_sessions_count_personaltraining_sessions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupWorkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название тренировки')),
                ('branch', models.CharField(choices=[('dvor', 'Дворцовая 4А'), ('repina', 'ул. Репина 4'), ('lenina', 'пр. Ленинского Комсомола 34')], max_length=20, verbose_name='Филиал')),
                ('trainer', models.CharField(max_length=100, verbose_name='Тренер')),
                ('description', models.TextField(verbose_name='Описание')),
                ('time', models.CharField(max_length=50, verbose_name='Время')),
                ('days', models.CharField(max_length=100, verbose_name='Дни недели')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
        ),
    ]
