# Generated by Django 5.2.1 on 2025-05-13 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainfitnes', '0006_groupworkout'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('content', models.TextField(verbose_name='Отзыв')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
            ],
        ),
    ]
