# Generated by Django 5.2.1 on 2025-05-16 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainfitnes', '0010_subscriptionrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_id', models.CharField(max_length=100)),
                ('subscription_title', models.CharField(max_length=255)),
                ('subscription_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('card_number', models.CharField(max_length=4)),
                ('card_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
